// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// By default, load .env.local first (local development overrides)
// and fall back to .env. If MIGRATE_TO_PROD is set, we bypass .env.local
// to target the production Neon database in .env.
if (process.env.MIGRATE_TO_PROD === "true") {
  dotenv.config({ path: ".env" });
} else {
  dotenv.config({ path: ".env.local" });
  dotenv.config({ path: ".env" });
}

// Safety check to prevent running development commands against Neon production database
const isDevCommand = process.argv.includes("dev") || process.argv.includes("reset");
const isProductionDb = process.env.DATABASE_URL?.includes("neon.tech");
if (isDevCommand && isProductionDb) {
  throw new Error(
    "CRITICAL WARNING: You are attempting to run a development command (migrate dev / reset) against the production Neon database. Command aborted."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
